import type { Metadata } from "next"
import Link from "next/link"
import { ArrowLeft, Building } from "lucide-react"

import NetOperatingIncomeCalculator from "@/components/calculators/real-estate/net-operating-income"
import { Separator } from "@/components/ui/separator"

export const metadata: Metadata = {
  title: "Free Net Operating Income (NOI) Calculator | Real Estate Investment Tool",
  description:
    "Calculate your property's Net Operating Income (NOI) with our free calculator. Analyze rental income, expenses, and property value estimates for better investment decisions.",
  keywords: [
    "net operating income calculator",
    "NOI calculator",
    "real estate investment calculator",
    "property income calculator",
    "rental property analysis",
    "free NOI calculator",
    "property expense calculator",
  ],
}

export default function NetOperatingIncomePage() {
  return (
    <div className="container mx-auto px-4 py-8">
      <div className="mb-8">
        <Link
          href="/calculators/real-estate"
          className="flex items-center gap-2 text-muted-foreground hover:text-primary mb-4"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to Real Estate Calculators
        </Link>
        <div className="flex items-center gap-3 mb-2">
          <Building className="h-8 w-8 text-primary" />
          <h1 className="text-3xl font-bold tracking-tight">Net Operating Income (NOI) Calculator</h1>
        </div>
        <p className="text-muted-foreground">Calculate the profitability of income-generating real estate properties</p>
      </div>

      <div className="mb-8">
        <NetOperatingIncomeCalculator />
      </div>

      <Separator className="my-8" />

      <div className="space-y-6 mb-8">
        <h2 className="text-2xl font-bold tracking-tight">About Net Operating Income</h2>
        <p>
          Net Operating Income (NOI) is one of the most important metrics in real estate investment analysis. It
          represents the annual income generated by a property after deducting all operating expenses, but before
          accounting for taxes, financing costs, capital expenditures, and depreciation.
        </p>

        <h3 className="text-xl font-semibold mt-6">How to Calculate NOI</h3>
        <p>The formula for calculating Net Operating Income is:</p>
        <div className="bg-muted p-4 rounded-md my-4">
          <p className="font-medium">NOI = Effective Gross Income - Operating Expenses</p>
        </div>
        <p>Where:</p>
        <ul className="list-disc list-inside space-y-2 ml-4">
          <li>
            <strong>Effective Gross Income (EGI)</strong> = Potential Gross Income - Vacancy and Credit Losses + Other
            Income
          </li>
          <li>
            <strong>Operating Expenses</strong> = All expenses necessary to operate and maintain the property
          </li>
        </ul>

        <h3 className="text-xl font-semibold mt-6">Why NOI Matters</h3>
        <p>NOI is crucial for several reasons:</p>
        <ul className="list-disc list-inside space-y-2 ml-4">
          <li>It provides a clear picture of a property's ability to generate income</li>
          <li>It's used to calculate the capitalization rate (Cap Rate = NOI ÷ Property Value)</li>
          <li>Lenders use it to determine the Debt Service Coverage Ratio (DSCR = NOI ÷ Annual Debt Service)</li>
          <li>It helps investors compare different properties on an equal basis</li>
          <li>It's used in property valuation through the income approach</li>
        </ul>

        <h3 className="text-xl font-semibold mt-6">What's Not Included in NOI</h3>
        <p>It's important to understand what NOI does NOT include:</p>
        <ul className="list-disc list-inside space-y-2 ml-4">
          <li>Mortgage payments (principal and interest)</li>
          <li>Income taxes</li>
          <li>Depreciation and amortization</li>
          <li>Capital expenditures (major improvements)</li>
          <li>Owner's personal expenses</li>
        </ul>

        <h3 className="text-xl font-semibold mt-6">Using Our NOI Calculator</h3>
        <p>Our free Net Operating Income calculator helps you:</p>
        <ul className="list-disc list-inside space-y-2 ml-4">
          <li>Calculate your property's NOI quickly and accurately</li>
          <li>Break down income and expenses visually</li>
          <li>Estimate property value based on NOI and cap rate</li>
          <li>Analyze expense ratios and financial performance</li>
          <li>Make better-informed investment decisions</li>
        </ul>
      </div>
    </div>
  )
}

